language: python
python:
  - "3.7.6"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - travis_wait 30 mvn install
  - conda env create -q -f tests/files/testing_env.yaml
  - conda activate testing_env
  - python -m pip install .
script: 
  - bats tests/test_juno-typing.bats
